version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: amdr_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: CDMO
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: itriacs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: amdr_redis
    restart: unless-stopped
    command: redis-server --requirepass qagv
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: amdr_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
